VS/FinanceW/FinanceW/Controllers/BanksController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using FinanceW.Models;

namespace FinanceW.Controllers
{
    public class BanksController : Controller
    {
        private readonly FinanceWContext _context;

        public BanksController(FinanceWContext context)
        {
            _context = context;
        }

        // GET: Banks
        public async Task<IActionResult> Index()
        {
            return View(await _context.Banks.ToListAsync());
        }

        // GET: Banks/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var bank = await _context.Banks
                .SingleOrDefaultAsync(m => m.BankId == id);
            if (bank == null)
            {
                return NotFound();
            }

            return View(bank);
        }

        // GET: Banks/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Banks/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("BankId,Description,Country,StatusBank")] Bank bank)
        {
            if (ModelState.IsValid)
            {
                _context.Add(bank);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(bank);
        }

        // GET: Banks/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var bank = await _context.Banks.SingleOrDefaultAsync(m => m.BankId == id);
            if (bank == null)
            {
                return NotFound();
            }
            return View(bank);
        }

        // POST: Banks/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("BankId,Description,Country,StatusBank")] Bank bank)
        {
            if (id != bank.BankId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(bank);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BankExists(bank.BankId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(bank);
        }

        // GET: Banks/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var bank = await _context.Banks
                .SingleOrDefaultAsync(m => m.BankId == id);
            if (bank == null)
            {
                return NotFound();
            }

            return View(bank);
        }

        // POST: Banks/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var bank = await _context.Banks.SingleOrDefaultAsync(m => m.BankId == id);
            _context.Banks.Remove(bank);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BankExists(int id)
        {
            return _context.Banks.Any(e => e.BankId == id);
        }
    }
}

VS/FinanceW/FinanceW/Views/Shared/AccessDenied.cshtml
@{
    ViewData["Title"] = "AccessDenied";
}

<h2>AccessDenied</h2>

VS/FinanceW/FinanceW/Views/Shared/_Layout.cshtml
@inject UserManager<ApplicationUser> UserManager
@*@{
        IList<System.Security.Claims.Claim> claims;
        claims = null;
        if (User.Identity.IsAuthenticated)
        {
            var appUser = await UserManager.GetUserAsync(User);
            claims = await UserManager.GetClaimsAsync(appUser);
        }
    }*@

@*<!DOCTYPE html>*@
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FinanceW</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">FinanceW</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    @if (User.Claims.Any(c => c.Type == "ADMIN" && c.Value == "X"))
                    {
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Administración<span class="caret"></span></a>
                            <ul class="dropdown-menu" role="menu">
                                <li><a asp-area="" asp-controller="Banks" asp-action="Index">Bancos</a></li>
                                <li><a asp-area="" asp-controller="Currencies" asp-action="Index">Monedas</a></li>
                                <li><a asp-area="" asp-controller="CurrencyConverts" asp-action="Index">Equivalencia entre Monedas</a></li>
                                <li class="divider"></li>
                                <li><a asp-area="" asp-controller="ReminderTypes" asp-action="Index">Tipos de Recordatorios</a></li>
                                <li class="divider"></li>
                                <li><a asp-area="" asp-controller="UsersClaims" asp-action="Index">Users Claims</a></li>

                            </ul>
                        </li>
                    }
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Registro de Productos<span class="caret"></span></a>
                            <ul class="dropdown-menu" role="menu">
                                <li> <a asp-area="" asp-controller="Products" asp-action="Index">Productos</a>
                                <li><a asp-area="" asp-controller="Expenses" asp-action="Index">Gastos Recurrentes</a></li>
                                <li class="divider"></li>
                                <li><a asp-area="" asp-controller="CreditCardCuts" asp-action="Index">Corte de tarjeta de crédito</a></li>
                            </ul>
                        </li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Transacciones<span class="caret"></span></a>
                            <ul class="dropdown-menu" role="menu">
                                <li><a asp-area="" asp-controller="CashIncomes" asp-action="Index">Ingreso de Efectivo</a></li>
                                <li><a asp-area="" asp-controller="CashOutcomes" asp-action="Index">Registrar de Gastos</a></li>
                                <li><a asp-area="" asp-controller="PayExpenses" asp-action="Index">Pago de Gastos Recurrentes</a></li>
                                <li><a asp-area="" asp-controller="PayLoans" asp-action="Index">Pago de Préstamos</a></li>
                                <li><a asp-area="" asp-controller="PayCreditCards" asp-action="Index">Pago de Tarjetas de Crédito</a></li>
                                <li class="divider"></li>
                                <li><a asp-area="" asp-controller="PaymentReminders" asp-action="Index">Recordatorios de Pagos</a></li>
                            </ul>
                        </li>
                    }
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                </ul>
                @await Html.PartialAsync("_LoginPartial")
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - FinanceW</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>